spring:
  profiles:
    active: dev
  application:
    name: sbeam
  servlet:
    multipart:
      max-file-size: 5MB
  thymeleaf:
    prefix: classpath:/templates/
  resources:
    static-locations: file:${web.upload-path},classpath:/public
  mvc:
    static-path-pattern: /public/**
logging:
  path: ./
  file: ${logging.path}/sbeam.log
mybatis-plus:
  type-aliases-package: com.lumr.sbeam.vo