spring:
  profiles:
    active: dev
  application:
    name: sbeam
  servlet:
    multipart:
      max-file-size: 5MB
  thymeleaf:
    prefix: classpath:/templates/
  resources:
    static-locations: file:${web.upload-path},classpath:/public
  mvc:
    static-path-pattern: /public/**
  datasource:
    url: jdbc:mysql://localhost:3306/sbeam?characterEncoding=utf8&useSSL=false
    username: web
    password: www
logging:
  path: ${HOME}/logs
  file: ${logging.path}/sbeam.log
mybatis-plus:
  type-aliases-package: com.lumr.sbeam.vo
  mapper-locations: classpath:/mapper/*Mapper.xml,classpath:/mapper/*Dao.xml